/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package autogenerated.files

import dataexport.S3.inner.users.messages.webhook.Send

fun main() {
    Send.newBuilder().build()
}
